### ISSUE TITLE
Something went wrong pop-up

### ISSUE THREAD

**Issue by jemily11** [khalim19/gimp-plugin-export-layers#50]
Exporting layers just doesn't seem to like me, so I'm hoping I can get some help with it. This is the error message it's giving me.

Traceback (most recent call last):
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/__init__.py", line 276, in _run
    procedure(*procedure_params)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pggui.py", line 492, in func_wrapper
    func(self, *args, **kwargs)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/export_layers.py", line 70, in plug_in_export_layers
    _run_export_layers_interactive(layer_tree)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/export_layers.py", line 133, in _run_export_layers_interactive
    gui_plugin.export_layers_gui(layer_tree, SETTINGS)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/export_layers/gui/gui_plugin.py", line 1084, in export_layers_gui
    ExportLayersGui(image, settings)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/export_layers/gui/gui_plugin.py", line 329, in __init__
    self._init_gui()
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/export_layers/gui/gui_plugin.py", line 451, in _init_gui
    pgsetting.SettingGuiTypes.extended_entry, self._filename_pattern_entry]
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pgsettinggroup.py", line 504, in initialize_gui
    setting.set_gui(*set_gui_args)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pgsetting.py", line 461, in set_gui
    auto_update_gui_to_setting=auto_update_gui_to_setting)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pgsettingpresenters_gtk.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pgsettingpresenter.py", line 130, in __init__
    self._copy_state(old_setting_presenter)
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pgsettingpresenter.py", line 246, in _copy_state
    self._set_value(old_setting_presenter._get_value())
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pgsettingpresenters_gtk.py", line 153, in _set_value
    self._element.assign_text(value.encode(pgconstants.GTK_CHARACTER_ENCODING))
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pggui_entries.py", line 98, in assign_text
    self._assign_placeholder_text()
  File "/Users/user/Library/Application Support/GIMP/2.8/plug-ins/pygimplib/pggui_entries.py", line 139, in _assign_placeholder_text
    if self.get_realized():
AttributeError: 'FilenamePatternEntry' object has no attribute 'get_realized'

**Comment by khalim19** [comment]
Thank you for the report, I'll look into it.

I'll need more information, though, in order to track down the cause of the crash more effectively, especially:
* exact steps to reproduce the issue
* plug-in version
* operating system

**Comment by jemily11** [comment]
Hi there, I've since gotten it working. I have two gimps installed (2.0 and 2.8) and it works in one

Sent from my iPhone

On 3 Feb 2018, at 4:01 am, khalim19 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for the report, I'll look into it.

I'll need more information, though, in order to track down the cause of the crash more effectively, especially:

  *   exact steps to reproduce the issue
  *   plug-in version
  *   operating system

**Comment by khalim19** [comment]
Thanks for the heads-up. Forgot to ask about the GIMP version, the plug-in will definitely not work on versions lower than 2.8.
